name: neom_posts
description: Post creation and view for Cyberneom.
version: 1.3.0
homepage: https://github.com/Cyberneom/neom_posts
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  neom_commons:
    git:
      url: git@github.com:Cyberneom/neom_commons.git
  neom_timeline:
    git:
      url: git@github.com:Cyberneom/neom_timeline.git

  camera: ^0.11.1
  photo_manager: ^3.6.4
  fraction: ^5.0.4

  video_editor: ^3.0.0
#  easy_video_editor: ^0.0.7

#  video_trimmer: ^4.0.2
#  video_trimmer:
#    git:
#      url: https://github.com/samuel-kings/video_trimmer_fork.git
#  ffmpeg_kit_flutter_min: ^6.0.3
#  flutter_ffmpeg: ^0.4.2

#  ffmpeg_kit_flutter: ^6.0.3
#  ffmpeg_kit_min_gpl: ^6.0.3+1-LTS

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
