name: neom_posts
description: Post creation and view for Cyberneom.
version: 1.3.0
homepage: https://github.com/Cyberneom/neom_posts
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  neom_commons:
    git:
      url: git@github.com:Cyberneom/neom_commons.git
  neom_timeline:
    git:
      url: git@github.com:Cyberneom/neom_timeline.git

  camera: ^0.11.1
  photo_manager: ^3.6.4
  fraction: ^5.0.4

  #Post with only text
  auto_size_text_field: ^2.2.4

  video_editor: ^3.0.0
  easy_video_editor: ^0.1.2

  file_picker: ^10.1.2
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  flutter_image_compress: ^2.4.0
  video_compress: ^3.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
